[default]
DEBUG = false
EXTENSIONS = [
    # "studycards.ext.site:init_app",
    
]

[development]
DEBUG = true
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
EXTENSIONS = [
    # "studycards.ext.site:init_app",

]

[production]